services:
  mongo:
    image: mongo:7.0
    container_name: project_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db

volumes:
  mongo_data:
